import type { NextPage } from 'next';
import Head from 'next/head';
import { GridDisplay } from '../../components/GridDisplay/GridDisplay';
import { Layout } from '../../components/Layout/Layout';
import { ScreenOptions } from '../../components/ScreenOptions/ScreenOptions';
import { SourceAccordionList } from '../../components/SelectSource/SourceAccordionList';
import { useTeleContext } from '../../context/TeleContext';
import { useDisplayConfig } from '../../hooks/useDisplayConfig';
import { useSavedGrid } from '../../hooks/useSavedGrid';
import { MainLayout } from '../../layout/MainLayout';
import { Source } from '../../sources';
import { uuid } from '../../utils/uuid';
import { DisplayMode } from './types';

const MonitorPage: NextPage = () => {
  const { isEditing, editingSourceUuid, editingSourceIdx } = useTeleContext();
  const [, setSelectedSources] = useSavedGrid();
  const [displayConfig, setDisplayConfig] = useDisplayConfig();

  const handleModeChange = (mode: DisplayMode) => {
    if (mode === DisplayMode.Grid) {
      setDisplayConfig(cfg => ({
        ...cfg,
        mode,
        grid: { size: cfg.grid?.size || 4 }
      }));
    } else {
      setDisplayConfig(cfg => ({
        ...cfg,
        mode
      }));
    }
  };
  const handleSizeChange = (newSize: number) => {
    if (displayConfig.mode !== DisplayMode.Grid) return;
    setDisplayConfig(config => ({
      ...config,
      grid: { size: newSize }
    }));
  };

  const handleSourceAdd = () => {
    setSelectedSources(sources => [
      ...(sources || []),
      {
        sourceSlug: 'Barras',
        uuid: uuid()
      }
    ]);
  };

  const handleSourceChange = (source: Source) => {
    if (editingSourceIdx === undefined) return;
    console.log('editingSourceIdx', editingSourceIdx);
    setSelectedSources(sources => {
      if (!sources) return sources;
      if (sources.length < editingSourceIdx + 1) {
        for (let i = sources.length; i <= editingSourceIdx; i++) {
          sources[i] = { uuid: uuid() };
        }
      }
      return sources.map((src, idx) => {
        if (editingSourceIdx === idx)
          return { ...src, sourceSlug: source.slug };
        else return src;
      });
    });
  };

  return (
    <MainLayout>
      <Head>
        <title>Tele - Layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row">
        <div className={isEditing ? 'col-8' : 'col-12'}>
          <div className="row no-gutters row-canales">
            {displayConfig.mode === DisplayMode.Grid && (
              <GridDisplay size={displayConfig.grid?.size} />
            )}
            {displayConfig.mode === DisplayMode.Layout && (
              <Layout layout={displayConfig.layout} />
            )}
          </div>
        </div>
        {isEditing && (
          <>
            <div className="col-4 pr-4">
              <SourceAccordionList
                onSelect={handleSourceChange}
                selectedSourceSlug={editingSourceUuid}
              />
            </div>
            <ScreenOptions
              onSizeChange={handleSizeChange}
              onSourceAdd={
                displayConfig.mode === DisplayMode.Grid
                  ? handleSourceAdd
                  : undefined
              }
              onModeChange={handleModeChange}
              mode={displayConfig.mode}
              size={displayConfig.grid.size}
            />
          </>
        )}
      </div>
    </MainLayout>
  );
};

export default MonitorPage;
