import { ZappingChannel } from '@/lib/zapping';

/**
 * Offline snapshot of the Zapping catalogue, used as the seed/fallback for
 * `useZappingChannels` (which refreshes it from `channelswithurl`). Only read
 * before the first successful fetch, or if the endpoint is unreachable.
 */
export const canalesZapping: Record<string, ZappingChannel> = {
  "10": {
    id: 10,
    name: "Cámara de Diputados TV",
    image: "camara",
    desc_short: "Señal oficial de la Cámara de Diputados",
    package_id: 28,
    number: 160,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/diputados/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/diputados/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "102": {
    id: 102,
    name: "DW Español",
    image: "dwe",
    desc_short: "Noticias internacionales",
    package_id: 871,
    number: 135,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/dwes/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/dwes/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "104": {
    id: 104,
    name: "Arirang",
    image: "arirang",
    desc_short: "Entretención y cultura de Corea",
    package_id: 871,
    number: 141,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/arirang/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/arirang/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "106": {
    id: 106,
    name: "AMC",
    image: "amc",
    desc_short: "Cine y Series",
    package_id: 80,
    number: 114,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/amc/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/amc/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "108": {
    id: 108,
    name: "Film \u0026 Arts",
    image: "filmandarts",
    desc_short: "Cine, Series y arte",
    package_id: 581,
    number: 119,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/filmandart/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/filmandart/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "109": {
    id: 109,
    name: "Europa Europa",
    image: "europaeuropa",
    desc_short: "Cine y Series",
    package_id: 40,
    number: 118,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/europa/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/europa/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "11": {
    id: 11,
    name: "TV Senado",
    image: "tvsenado",
    desc_short: "Señal oficial del Senado",
    package_id: 40,
    number: 161,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/senado/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/senado/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "110": {
    id: 110,
    name: "El Gourmet",
    image: "elgourmet",
    desc_short: "Variedades",
    package_id: 581,
    number: 72,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/gourmet/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/gourmet/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "120": {
    id: 120,
    name: "Discovery",
    image: "discovery",
    desc_short: "Documentales y reportajes",
    package_id: 74,
    number: 60,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/discovery/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/discovery/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "121": {
    id: 121,
    name: "Discovery Kids",
    image: "discoverykids",
    desc_short: "Infantil",
    package_id: 40,
    number: 78,
    has_sub: true,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/discoverykids/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/discoverykids/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "122": {
    id: 122,
    name: "Home \u0026 Health",
    image: "homeandhealth",
    desc_short: "Estilo, salud y tendencias.",
    package_id: 80,
    number: 67,
    has_sub: true,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/homeandhealth/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/homeandhealth/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "123": {
    id: 123,
    name: "TLC",
    image: "tlc",
    desc_short: "Estilo y tendencias",
    package_id: 40,
    number: 66,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tlc/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tlc/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "124": {
    id: 124,
    name: "Turbo",
    image: "turbo",
    desc_short: "Automóviles y entretención",
    package_id: 571,
    number: 59,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/turbo/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/turbo/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "125": {
    id: 125,
    name: "TNT",
    image: "tnt",
    desc_short: "Películas y series de Hollywood",
    package_id: 571,
    number: 106,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tnt/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tnt/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "126": {
    id: 126,
    name: "TNT Series",
    image: "tntseries",
    desc_short: "Cine y Series",
    package_id: 581,
    number: 102,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tntseries/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tntseries/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "128": {
    id: 128,
    name: "Food Network",
    image: "food",
    desc_short: "Cocina y tendencias",
    package_id: 40,
    number: 71,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/foodnetwork/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/foodnetwork/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "129": {
    id: 129,
    name: "CNN Internacional",
    image: "cnni",
    desc_short: "Noticias internacionales",
    package_id: 581,
    number: 133,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cnni/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/cnni/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "13": {
    id: 13,
    name: "TV +",
    image: "tvmas",
    desc_short: "Entretención",
    package_id: 76,
    number: 18,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvm/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tvm/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "130": {
    id: 130,
    name: "CNN Español",
    image: "cnnespanol",
    desc_short: "Noticias en español",
    package_id: 871,
    number: 132,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cnnes/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/cnnes/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "131": {
    id: 131,
    name: "TCM",
    image: "tcm",
    desc_short: "Clásicos del cine",
    package_id: 581,
    number: 117,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tcm/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tcm/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "132": {
    id: 132,
    name: "Tooncast",
    image: "tooncast",
    desc_short: "Infantil",
    package_id: 40,
    number: 88,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tooncast/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tooncast/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "134": {
    id: 134,
    name: "Radio Romantica",
    image: "romantica",
    desc_short: "Radio Chile",
    package_id: 551,
    number: 196,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/romantica/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/romantica/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "135": {
    id: 135,
    name: "Carolina TV",
    image: "carolinatv",
    desc_short: "Radio Online Chile",
    package_id: 581,
    number: 195,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/carolinatv/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/carolinatv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "136": {
    id: 136,
    name: "Radio Infinita",
    image: "radioinfinita",
    desc_short: "Radio Chile",
    package_id: 40,
    number: 197,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/infinitatv/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/infinitatv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "138": {
    id: 138,
    name: "Cartoon Network",
    image: "cn",
    desc_short: "Infantil",
    package_id: 74,
    number: 86,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cn/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/cn/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "142": {
    id: 142,
    name: "CNN Chile",
    image: "cnnchile",
    desc_short: "Noticias de Chile",
    package_id: 871,
    number: 8,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cnnchile/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/cnnchile/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "146": {
    id: 146,
    name: "Space",
    image: "space",
    desc_short: "Películas y boxeo",
    package_id: 40,
    number: 111,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/space/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/space/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "147": {
    id: 147,
    name: "Investigation Discovery",
    image: "investigation",
    desc_short: "Suspenso e investigación",
    package_id: 691,
    number: 55,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/id/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/id/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "148": {
    id: 148,
    name: "Animal Planet",
    image: "animalplanet",
    desc_short: "Documentales y naturaleza",
    package_id: 28,
    number: 63,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/animalplanet/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/animalplanet/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "153": {
    id: 153,
    name: "Home \u0026 Garden",
    image: "homeandgarden",
    desc_short: "Estilo y tendencias",
    package_id: 911,
    number: 68,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hgtv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hgtv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "156": {
    id: 156,
    name: "TNT Sports",
    image: "tntsports3",
    desc_short: "Deportes",
    package_id: 911,
    number: 35,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tntsports3_ll/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/tntsports3_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1592": {
    id: 1592,
    name: "TNT Novelas",
    image: "tntnovelas",
    desc_short: "Canal de telenovelas.",
    package_id: 761,
    number: 121,
    has_sub: true,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tntnovelas/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tntnovelas/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1602": {
    id: 1602,
    name: "Adult Swim",
    image: "adultswim",
    desc_short:
      "Canal de humor y animación orientado en adolescentes y adultos jóvenes.",
    package_id: 80,
    number: 92,
    has_sub: true,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/adultswim/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/adultswim/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1622": {
    id: 1622,
    name: "Mega 2",
    image: "mega2",
    desc_short: "Actualidad, deporte y tendencias.",
    package_id: 28,
    number: 27,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/mega2/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/mega2/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "163": {
    id: 163,
    name: "RT Español",
    image: "rt",
    desc_short: "Noticias internacionales",
    package_id: 80,
    number: 138,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/rtes/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/rtes/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "164": {
    id: 164,
    name: "TNT Sports Premium",
    image: "tntsportshd",
    desc_short: "Deportes",
    package_id: 92,
    number: 36,
    has_sub: false,
    has_hd: true,
    catch_up: 3,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tntsportshd_ll/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/tntsportshd_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "165": {
    id: 165,
    name: "La Red",
    image: "lared",
    desc_short: "Entretención",
    package_id: 74,
    number: 28,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/lared/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/lared/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "166": {
    id: 166,
    name: "Disney Channel",
    image: "disneychannel",
    desc_short: "Canal Infantil",
    package_id: 761,
    number: 87,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/disney/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/disney/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "168": {
    id: 168,
    name: "Disney Junior",
    image: "disneyjr",
    desc_short: "Canal Infantil",
    package_id: 871,
    number: 77,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/disneyjr/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/disneyjr/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "169": {
    id: 169,
    name: "ESPN",
    image: "espn",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 28,
    number: 41,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espn_ll/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/espn_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "17": {
    id: 17,
    name: "Canal 9 Bío-Bío",
    image: "canal9",
    desc_short: "Señal de la Octava Región",
    package_id: 581,
    number: 179,
    has_sub: false,
    has_hd: false,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://unlimited1-cl-isp.dps.live/c9/c9.smil/playlist.m3u8",
    url_sub: "https://unlimited1-cl-isp.dps.live/c9/c9.smil/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "170": {
    id: 170,
    name: "ESPN 2",
    image: "espn2",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 581,
    number: 42,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espn2_ll/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/espn2_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "171": {
    id: 171,
    name: "ESPN 3",
    image: "espn3",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 28,
    number: 43,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espn3_ll/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/espn3_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "172": {
    id: 172,
    name: "ESPN 4",
    image: "espn4",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 571,
    number: 44,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espnplus_ll/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/espnplus_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1722": {
    id: 1722,
    name: "Zapping Music Soft Pop",
    image: "music-softpop",
    desc_short: "El mejor pop tranqui en tu hogar",
    package_id: 79,
    number: 202,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-softpop/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zm-softpop/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "173": {
    id: 173,
    name: "ETC",
    image: "etc",
    desc_short: "Canal del animé",
    package_id: 571,
    number: 90,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/etctv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/etctv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1732": {
    id: 1732,
    name: "TLNovelas",
    image: "tlnovelas",
    desc_short: "Las mejores telenovelas.",
    package_id: 581,
    number: 122,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tlnovelas/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tlnovelas/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1742": {
    id: 1742,
    name: "Las Estrellas",
    image: "lasestrellas",
    desc_short: "Canal mexicano de telenovelas y entretenimiento.",
    package_id: 581,
    number: 123,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/lasestrellas/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/lasestrellas/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1752": {
    id: 1752,
    name: "Golden",
    image: "goldenplus",
    desc_short: "Películas y series para todos.",
    package_id: 571,
    number: 112,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/goldenplus/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/goldenplus/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1762": {
    id: 1762,
    name: "Love Nature",
    image: "lovenaturecl",
    desc_short: "Naturaleza en HD",
    package_id: 581,
    number: 64,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/lovenaturecl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/lovenaturecl/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1772": {
    id: 1772,
    name: "ZooMoo",
    image: "zoomoocl",
    desc_short: "Educación entretenida para los más pequeños.",
    package_id: 581,
    number: 82,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zoomoocl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zoomoocl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1782": {
    id: 1782,
    name: "Univisión",
    image: "univision",
    desc_short: "Lo mejor de Televisa",
    package_id: 581,
    number: 124,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/univision/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/univision/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1792": {
    id: 1792,
    name: "MTV",
    image: "mtv",
    desc_short: "Canal de música.",
    package_id: 691,
    number: 94,
    has_sub: false,
    has_hd: true,
    catch_up: 3,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/mtv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/mtv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1802": {
    id: 1802,
    name: "Zona Latina",
    image: "zonalatinacl",
    desc_short: "Canal de programación variada.",
    package_id: 581,
    number: 31,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zonalatinacl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zonalatinacl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "181": {
    id: 181,
    name: "UESTV",
    image: "uestv",
    desc_short: "Canal local",
    package_id: 911,
    number: 172,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/uestvcl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/uestvcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1812": {
    id: 1812,
    name: "Via X",
    image: "viaxcl",
    desc_short: "Actualidad.",
    package_id: 911,
    number: 30,
    has_sub: false,
    has_hd: true,
    catch_up: 3,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/viaxcl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/viaxcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "182": {
    id: 182,
    name: "TV USACH",
    image: "stgotv",
    desc_short: "Canal local",
    package_id: 28,
    number: 173,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/stgotv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/stgotv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "1822": {
    id: 1822,
    name: "TyC Sports",
    image: "tycsports",
    desc_short: "Programas en vivo y de producción propia",
    package_id: 911,
    number: 49,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tycsports/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tycsports/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "185": {
    id: 185,
    name: "Discovery World",
    image: "d-world1",
    desc_short: "Cultura",
    package_id: 691,
    number: 65,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/world/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/world/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "186": {
    id: 186,
    name: "Discovery Science",
    image: "d-science",
    desc_short: "Cultura",
    package_id: 80,
    number: 62,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/science/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/science/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "187": {
    id: 187,
    name: "Discovery Theater",
    image: "d-theater",
    desc_short: "Cultura",
    package_id: 691,
    number: 61,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/theater/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/theater/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "189": {
    id: 189,
    name: "Zapping Music LOF-AI",
    image: "music-lofi",
    desc_short:
      "Solo pasa acá a relajarte con la mejor selección de música Lo-Fi",
    package_id: 911,
    number: 201,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-lofi/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zm-lofi/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "193": {
    id: 193,
    name: "France 24",
    image: "fr24es",
    desc_short: "Noticias globales desde una perspectiva francesa.",
    package_id: 761,
    number: 136,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/france24/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/france24/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "195": {
    id: 195,
    name: "Golf Channel",
    image: "golf",
    desc_short: "Canal Deportivo",
    package_id: 571,
    number: 50,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/golfchannel/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/golfchannel/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "196": {
    id: 196,
    name: "Allegro",
    image: "allegro",
    desc_short: "Música Clasica",
    package_id: 80,
    number: 199,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/allegro/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/allegro/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "197": {
    id: 197,
    name: "Eurochannel",
    image: "euro",
    desc_short: "Películas y series",
    package_id: 74,
    number: 120,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/eurochannel/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/eurochannel/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "198": {
    id: 198,
    name: "Sony Channel",
    image: "sony",
    desc_short: "Series y películas",
    package_id: 761,
    number: 103,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/sony/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/sony/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "199": {
    id: 199,
    name: "Warner Channel",
    image: "warner",
    desc_short: "Series y películas",
    package_id: 871,
    number: 101,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/warner/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/warner/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "200": {
    id: 200,
    name: "AXN",
    image: "axn",
    desc_short: "Series y películas",
    package_id: 581,
    number: 105,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/axn/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/axn/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "201": {
    id: 201,
    name: "E!",
    image: "e",
    desc_short: "Entretenimiento",
    package_id: 871,
    number: 70,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/e/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/e/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "202": {
    id: 202,
    name: "Bio Bio TV",
    image: "biobio",
    desc_short: "Canal local",
    package_id: 40,
    number: 10,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/biobiotv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/biobiotv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "203": {
    id: 203,
    name: "ITV",
    image: "itv",
    desc_short: "Canal regional",
    package_id: 74,
    number: 185,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/itv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/itv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "204": {
    id: 204,
    name: "Tevex",
    image: "tevex",
    desc_short: "Canal local",
    package_id: 551,
    number: 162,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tevex/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tevex/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "205": {
    id: 205,
    name: "Universal TV",
    image: "universal",
    desc_short: "Series y películas",
    package_id: 871,
    number: 104,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/uc/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/uc/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "206": {
    id: 206,
    name: "Studio Universal",
    image: "suc",
    desc_short: "Series y películas",
    package_id: 40,
    number: 109,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/suc/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/suc/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "207": {
    id: 207,
    name: "USA Network",
    image: "syfy",
    desc_short: "Series y películas",
    package_id: 691,
    number: 113,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/syfy/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/syfy/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "208": {
    id: 208,
    name: "Radio Hoy",
    image: "radiohoy",
    desc_short: "El Sonido de tu vida.",
    package_id: 571,
    number: 198,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/radiohoy/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/radiohoy/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "209": {
    id: 209,
    name: "History",
    image: "history",
    desc_short: "Cultura",
    package_id: 691,
    number: 57,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/history/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/history/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "210": {
    id: 210,
    name: "H2",
    image: "h2",
    desc_short: "Cultura",
    package_id: 871,
    number: 58,
    has_sub: true,
    has_hd: true,
    catch_up: 3,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/h2/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/h2/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "211": {
    id: 211,
    name: "Lifetime",
    image: "lifetime",
    desc_short: "Variedades",
    package_id: 581,
    number: 56,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/lifetime/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/lifetime/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "215": {
    id: 215,
    name: "A3Series",
    image: "a3series",
    desc_short: "Series y películas",
    package_id: 571,
    number: 116,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/a3series/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/a3series/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "216": {
    id: 216,
    name: "A\u0026E",
    image: "aande",
    desc_short: "Series y películas",
    package_id: 871,
    number: 115,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/aande/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/aande/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "217": {
    id: 217,
    name: "telemundo",
    image: "telemundo",
    desc_short: "Series y películas",
    package_id: 871,
    number: 125,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/telemundo/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/telemundo/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "222": {
    id: 222,
    name: "Zapping Mix",
    image: "zmix",
    desc_short: "TVN, Chilevisión, Mega y Canal 13",
    package_id: 74,
    number: 17,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zc1/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zc1/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "225": {
    id: 225,
    name: "Zapping Channel",
    image: "zapping-channel1",
    desc_short: "Canal de los Zappiners",
    package_id: 871,
    number: 16,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zc2/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zc2/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "231": {
    id: 231,
    name: "Antena 3 Internacional",
    image: "a3int",
    desc_short: "Canal internacional",
    package_id: 691,
    number: 130,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/a3int/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/a3int/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "232": {
    id: 232,
    name: "HBO",
    image: "hbo",
    desc_short: "Series y películas",
    package_id: 581,
    number: 145,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbo/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbo/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "233": {
    id: 233,
    name: "HBO 2",
    image: "hbo2",
    desc_short: "Series y películas",
    package_id: 871,
    number: 100,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbo2/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbo2/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "234": {
    id: 234,
    name: "HBO Plus",
    image: "hboplus",
    desc_short: "Series y películas",
    package_id: 881,
    number: 148,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hboplus/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hboplus/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "235": {
    id: 235,
    name: "HBO Pop",
    image: "hbopop",
    desc_short: "Series y películas",
    package_id: 581,
    number: 151,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbopop/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbopop/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "236": {
    id: 236,
    name: "HBO Mundi",
    image: "hbomundi",
    desc_short: "Series y películas",
    package_id: 581,
    number: 152,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbomundi/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbomundi/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "237": {
    id: 237,
    name: "HBO Xtreme",
    image: "hboxtreme",
    desc_short: "Series y películas",
    package_id: 881,
    number: 149,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hboxtreme/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hboxtreme/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "238": {
    id: 238,
    name: "Cinemax",
    image: "cinemax",
    desc_short: "Series y películas",
    package_id: 581,
    number: 107,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cinemax/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/cinemax/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "239": {
    id: 239,
    name: "HBO Family",
    image: "hbofamily",
    desc_short: "Series y películas",
    package_id: 581,
    number: 147,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbofamily/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbofamily/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "2391": {
    id: 2391,
    name: "CHV Noticias",
    image: "chvnoticias",
    desc_short: "Noticias",
    package_id: 911,
    number: 11,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/chvnoticias/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/chvnoticias/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "240": {
    id: 240,
    name: "HBO Signature",
    image: "hbosignature",
    desc_short: "Series y películas",
    package_id: 581,
    number: 150,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbosignature/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbosignature/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "250": {
    id: 250,
    name: "NHK World Japan",
    image: "nhk",
    desc_short: "Canal internacional",
    package_id: 871,
    number: 140,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/nhk/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/nhk/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "252": {
    id: 252,
    name: "Nickelodeon",
    image: "nickelodeon",
    desc_short:
      "Canal especializado en animación, series y películas para jovenes y niños.",
    package_id: 581,
    number: 85,
    has_sub: true,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/nickelodeon/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/nickelodeon/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "253": {
    id: 253,
    name: "Nick Jr.",
    image: "nickjr",
    desc_short: "Canal con programación para los más pequeños de la casa.",
    package_id: 691,
    number: 76,
    has_sub: true,
    has_hd: true,
    catch_up: 4,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/nickjr/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/nickjr/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "254": {
    id: 254,
    name: "Dreamworks",
    image: "dreamworks",
    desc_short: "Infantil",
    package_id: 571,
    number: 81,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/dreamworks/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/dreamworks/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "255": {
    id: 255,
    name: "Comedy Central",
    image: "comedy",
    desc_short: "Comedia variada.",
    package_id: 28,
    number: 93,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/comedy/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/comedy/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "2551": {
    id: 2551,
    name: "Meganoticias",
    image: "meganoticias",
    desc_short:
      "Canal chileno de noticias y eventos nacionales e internacionales",
    package_id: 571,
    number: 9,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/meganoticias/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/meganoticias/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "257": {
    id: 257,
    name: "Playboy",
    image: "playboy",
    desc_short: "Adultos",
    package_id: 85,
    number: 144,
    has_sub: false,
    has_hd: true,
    catch_up: 3,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/playboy/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/playboy/live1/playlist.m3u8",
    parental: 1,
    locked: false,
  },
  "277": {
    id: 277,
    name: "Sony Movies",
    image: "sonymovies",
    desc_short: "Variedad cinematográfica.",
    package_id: 871,
    number: 108,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/sonymovies/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/sonymovies/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "279": {
    id: 279,
    name: "TVR",
    image: "tvr",
    desc_short: "Televisión Regional de Chile",
    package_id: 691,
    number: 175,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvr/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tvr/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "280": {
    id: 280,
    name: "TVU",
    image: "tvu",
    desc_short: "Televisión Universidad de Concepción",
    package_id: 74,
    number: 180,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvu/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tvu/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "282": {
    id: 282,
    name: "Antofagasta TV",
    image: "antofagastatv",
    desc_short: "Antofagasta TV",
    package_id: 40,
    number: 167,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/antofagastatv/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/antofagastatv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "283": {
    id: 283,
    name: "VTV Quillota",
    image: "vtvquillota",
    desc_short: "VTV Quillota",
    package_id: 571,
    number: 170,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/vtvquillota/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/vtvquillota/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "284": {
    id: 284,
    name: "Canal 2 Quellón",
    image: "c2quellon",
    desc_short: "Canal 2 Quellón",
    package_id: 871,
    number: 183,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/c2quellon/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/c2quellon/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "285": {
    id: 285,
    name: "TeleAngol",
    image: "teleangol",
    desc_short: "TeleAngol",
    package_id: 102,
    number: 182,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: true,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/teleangol/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/teleangol/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "286": {
    id: 286,
    name: "Canal 2 San Antonio",
    image: "c2sanantonio",
    desc_short: "Canal 2 San Antonio",
    package_id: 581,
    number: 178,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/c2sanantonio/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/c2sanantonio/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "287": {
    id: 287,
    name: "Patagonia Radio Televisión",
    image: "patagoniartv",
    desc_short: "Patagonia Radio Televisión",
    package_id: 571,
    number: 186,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/patagoniartv/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/patagoniartv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "288": {
    id: 288,
    name: "Senpai TV",
    image: "senpaitv",
    desc_short: "Canal de animación japonesa",
    package_id: 551,
    number: 91,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/senpaitv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/senpaitv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "289": {
    id: 289,
    name: "Mega Ficción",
    image: "megaficcion",
    desc_short: "Variedad de series y producciones de ficción",
    package_id: 40,
    number: 26,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/megaficcion/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/megaficcion/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "290": {
    id: 290,
    name: "El Centro TV",
    image: "centrotv",
    desc_short: "El Centro TV",
    package_id: 691,
    number: 174,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/centrotv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/centrotv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "291": {
    id: 291,
    name: "Mi Radio TV",
    image: "miradiotv",
    desc_short: "Mi Radio TV",
    package_id: 28,
    number: 165,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/miradiotv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/miradiotv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "292": {
    id: 292,
    name: "Agricultura TV ",
    image: "agriculturatv",
    desc_short: "Agricultura TV ",
    package_id: 561,
    number: 166,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/agriculturatv/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/agriculturatv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "293": {
    id: 293,
    name: "ISB",
    image: "isb",
    desc_short: "ISB",
    package_id: 871,
    number: 176,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/isb/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/isb/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "3": {
    id: 3,
    name: "Canal 13",
    image: "canal13",
    desc_short: "Variedad de programas para toda la familia.",
    package_id: 74,
    number: 22,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/13_ll/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/13_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "3151": {
    id: 3151,
    name: "La Metro FM",
    image: "lametro",
    desc_short: "Noticias del entretenimiento y segmentos interactivos.",
    package_id: 551,
    number: 194,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/lametro/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/lametro/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "3911": {
    id: 3911,
    name: "HBO 2",
    image: "hbo2b",
    desc_short: "Series y películas",
    package_id: 581,
    number: 146,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hbo2/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hbo2/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "4": {
    id: 4,
    name: "Mega",
    image: "mega",
    desc_short: "Emocionantes programas para toda la familia.",
    package_id: 74,
    number: 20,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/mega/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/mega/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "4771": {
    id: 4771,
    name: "Marga Marga TV",
    image: "margamargatv",
    desc_short: "Señal de la 5ta región. Canal de entretención",
    package_id: 911,
    number: 168,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/margamargatv/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/margamargatv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "4781": {
    id: 4781,
    name: "La Nuestra, radio streaming",
    image: "lanuestracl",
    desc_short: "Entretenimiento y compañía para divertirte todo el día",
    package_id: 40,
    number: 193,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/lanuestracl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/lanuestracl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "4791": {
    id: 4791,
    name: "Visión Plus TV",
    image: "visionplus",
    desc_short: "Entretenimiento, educación y cultura",
    package_id: 40,
    number: 171,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/visionplus/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/visionplus/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "4861": {
    id: 4861,
    name: "UChileTV",
    image: "uchiletvcl",
    desc_short: "Actualidad y cultura nacional.",
    package_id: 40,
    number: 163,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/uchiletvcl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/uchiletvcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5": {
    id: 5,
    name: "TVN",
    image: "tvn",
    desc_short: "Diversidad de contenidos televisivos.",
    package_id: 74,
    number: 19,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvno/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tvno/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5061": {
    id: 5061,
    name: "Telefe",
    image: "telefecl",
    desc_short: "Entretenimiento y noticias de Argentina.",
    package_id: 581,
    number: 129,
    has_sub: false,
    has_hd: true,
    catch_up: 4,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/telefecl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/telefecl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5071": {
    id: 5071,
    name: "MegaTiempo",
    image: "megatiempo",
    desc_short: "MegaTiempo, el primer canal del tiempo en Chile.",
    package_id: 76,
    number: 12,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/megatiempo/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/megatiempo/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "51": {
    id: 51,
    name: "13C",
    image: "13cable",
    desc_short: "Cultura, viajes y cocina",
    package_id: 76,
    number: 23,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/13c/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/13c/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "52": {
    id: 52,
    name: "24 Horas",
    image: "24horas",
    desc_short: "Noticias de Chile y el mundo 24/7",
    package_id: 561,
    number: 7,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/24h/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/24h/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5341": {
    id: 5341,
    name: "VePlus",
    image: "veplus",
    desc_short: "Telenovelas, talkshows y variedades.",
    package_id: 80,
    number: 127,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/veplus/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/veplus/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5361": {
    id: 5361,
    name: "Puranoticia",
    image: "puranoticiacl",
    desc_short: "Noticias con identidad regional.",
    package_id: 911,
    number: 177,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/puranoticiacl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/puranoticiacl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5431": {
    id: 5431,
    name: "Porcel TV",
    image: "porceltvcl",
    desc_short: "Canal de streaming que combina frescura, alegría y energía.",
    package_id: 551,
    number: 220,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/porceltvcl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/porceltvcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5441": {
    id: 5441,
    name: "AE Radio",
    image: "aeradiocl",
    desc_short: "AE Radio, la radio streaming del DuocUC",
    package_id: 911,
    number: 192,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/aeradiocl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/aeradiocl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5451": {
    id: 5451,
    name: "15.1",
    image: "canal15cl",
    desc_short: "Canal con valores cristianos.",
    package_id: 79,
    number: 184,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/canal15cl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/canal15cl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "57": {
    id: 57,
    name: "Zapping Music Chile",
    image: "music-chile",
    desc_short: "Lo más escuchado de la música chilena",
    package_id: 79,
    number: 209,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-chile/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zm-chile/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5841": {
    id: 5841,
    name: "Daystar",
    image: "daystar",
    desc_short: "Canal cristiano 24/7 que difunde el Evangelio.",
    package_id: 76,
    number: 159,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/daystar/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/daystar/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5951": {
    id: 5951,
    name: "travelxp",
    image: "travelxp",
    desc_short: "Explore el mundo desde de Travelxp",
    package_id: 881,
    number: 73,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/travelxp/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/travelxp/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "5991": {
    id: 5991,
    name: "AMC Series",
    image: "amcseries",
    desc_short: "Solo buenas historias.",
    package_id: 76,
    number: 99,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/amcseries/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/amcseries/en/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6": {
    id: 6,
    name: "Chilevisión",
    image: "chv",
    desc_short: "Entretenimiento, noticias y deportes.",
    package_id: 81,
    number: 21,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/chvsr_ll/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/chvsr_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "60": {
    id: 60,
    name: "Zapping Music Retro",
    image: "music-retro",
    desc_short: "La década dorada de los 80s",
    package_id: 551,
    number: 200,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-retro/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zm-retro/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6041": {
    id: 6041,
    name: "C5N",
    image: "c5ncl",
    desc_short:
      "Canal de noticias argentino con cobertura 24 horas de actualidad nacional e internacional.",
    package_id: 581,
    number: 128,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/c5ncl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/c5ncl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6111": {
    id: 6111,
    name: "France24",
    image: "france24frbr",
    desc_short: "Notícias 24 horas en francés.",
    package_id: 581,
    number: 137,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/france24frbr/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/france24frbr/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "62": {
    id: 62,
    name: "Zapping Music Hits",
    image: "music-hits",
    desc_short: "Los mejores éxitos de ayer y hoy ",
    package_id: 76,
    number: 208,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-hits/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zm-hits/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "63": {
    id: 63,
    name: "Zapping Music Rock",
    image: "music-rock",
    desc_short: "Guitarras y rock del mundo",
    package_id: 81,
    number: 207,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-rock/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zm-rock/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6381": {
    id: 6381,
    name: "Mix Noticias",
    image: "zpmixnewscl",
    desc_short: "Canal 24 horas, Meganoticias, CHV Noticias, T13 en vivo",
    package_id: 40,
    number: 6,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zpmixnewscl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zpmixnewscl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6481": {
    id: 6481,
    name: "A3Cine",
    image: "a3cine",
    desc_short:
      "Atrescine es el canal internacional de Atresmedia especializado en cine español.",
    package_id: 74,
    number: 98,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/a3cine/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/a3cine/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6501": {
    id: 6501,
    name: "¡Hola! TV",
    image: "holatv",
    desc_short:
      "La versión en pantalla de la famosa y reconocida revista ¡Hola!",
    package_id: 80,
    number: 95,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/holatv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/holatv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6511": {
    id: 6511,
    name: "Zapping Chill Pet",
    image: "zm-chillpets",
    desc_short: "Música relajante para tus mascotas.",
    package_id: 28,
    number: 205,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-chillpets/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zm-chillpets/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6531": {
    id: 6531,
    name: "Zapping Music Fiesta Latina",
    image: "zm-fiestalatina",
    desc_short: "Hits que te harán bailar.",
    package_id: 79,
    number: 204,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-fiestalatina/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zm-fiestalatina/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6551": {
    id: 6551,
    name: "CHV Contigo",
    image: "chvcontigocl",
    desc_short: "Viajes y sabores con el sello de cercanía de Chilevisión.",
    package_id: 871,
    number: 32,
    has_sub: false,
    has_hd: true,
    catch_up: 5,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/chvcontigocl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/chvcontigocl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6561": {
    id: 6561,
    name: "CHV de Culto",
    image: "chvdecultocl",
    desc_short: "Los programas más exitosos y recordados de Chilevisión.",
    package_id: 871,
    number: 33,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/chvdecultocl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/chvdecultocl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6581": {
    id: 6581,
    name: "Al Jazeera English",
    image: "aljazeeracl",
    desc_short: "Canal de noticias internacional en inglés con sede en Doha.",
    package_id: 871,
    number: 142,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/aljazeeracl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/aljazeeracl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6601": {
    id: 6601,
    name: "Plim Plim",
    image: "plimplimcl",
    desc_short: "Plim Plim: valores, aprendizaje y diversión asegurada",
    package_id: 76,
    number: 79,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/plimplimcl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/plimplimcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6621": {
    id: 6621,
    name: "Kanal D Drama",
    image: "kanaldedramacl",
    desc_short:
      "Es el primer y único canal que reúne los más exitosos e impactantes dramas turcos en tu idioma.",
    package_id: 40,
    number: 126,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/kanaldedramacl/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/kanaldedramacl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6751": {
    id: 6751,
    name: "Red Bull TV",
    image: "redbulltv",
    desc_short: "Vive la emoción con Red Bull TV.",
    package_id: 80,
    number: 15,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/redbulltv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/redbulltv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6791": {
    id: 6791,
    name: "Cartoonito",
    image: "cartoonito",
    desc_short: "Infantil.",
    package_id: 102,
    number: 83,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cartoonito/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/cartoonito/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6801": {
    id: 6801,
    name: "TVMas2",
    image: "tvmas2",
    desc_short: "Entretención.",
    package_id: 40,
    number: 164,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvmas2/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tvmas2/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6811": {
    id: 6811,
    name: "NTV",
    image: "ntv",
    desc_short: "Canal infantil familiar.",
    package_id: 74,
    number: 84,
    has_sub: false,
    has_hd: true,
    catch_up: 4,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/ntv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/ntv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6821": {
    id: 6821,
    name: "T13",
    image: "t13",
    desc_short: "Noticias de Chile y el mundo 24/7",
    package_id: 81,
    number: 13,
    has_sub: false,
    has_hd: true,
    catch_up: 3,
    reverse_epg: 1,
    start_over: true,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/t13/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/t13/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6831": {
    id: 6831,
    name: "ESPN 6",
    image: "espn6cl",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 861,
    number: 46,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espn6cl_ll/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/espn6cl_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6841": {
    id: 6841,
    name: "ESPN 7",
    image: "espn7cl",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 861,
    number: 47,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espn7cl_ll/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/espn7cl_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6861": {
    id: 6861,
    name: "ESPN Premium",
    image: "espnpremiumcl",
    desc_short: "Donde el deporte nunca se detiene.",
    package_id: 861,
    number: 48,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/espnpremiumcl_ll/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/espnpremiumcl_ll/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "6981": {
    id: 6981,
    name: "Cuenta Cuentos",
    image: "zm-cuentacuentos",
    desc_short:
      "Un grupo de voluntarios, dedican su tiempo a contar cuentos a los niños.",
    package_id: 871,
    number: 80,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-cuentacuentos/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zm-cuentacuentos/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7": {
    id: 7,
    name: "Teletrak",
    image: "teletrak",
    desc_short: "Vive la hípica",
    package_id: 911,
    number: 53,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/teletrak/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/teletrak/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7001": {
    id: 7001,
    name: "Hobbika",
    image: "hobikkacl",
    desc_short:
      "Hobbika es el canal donde encontrarás todas tus pasiones, en un solo lugar.",
    package_id: 561,
    number: 221,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/hobikkacl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/hobikkacl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7021": {
    id: 7021,
    name: "Zapping NOW",
    image: "zpnowcl",
    desc_short: "Acércate a lo mejor de los canales locales.",
    package_id: 871,
    number: 14,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zpnowcl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/zpnowcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7041": {
    id: 7041,
    name: "TV Brasil Internacional",
    image: "tvbrasilint",
    desc_short:
      "Señal internacional de TV Brasil dirigida a audiencias fuera de Brasil",
    package_id: 581,
    number: 143,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvbrasilint/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/tvbrasilint/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7051": {
    id: 7051,
    name: "Chilevisión Super Resolution",
    image: "chv4k",
    desc_short: "Entretenimiento, noticias y deportes.",
    package_id: 551,
    number: 4,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://violeta.zappingtv.com/block/sr-cfinal/playlist.m3u8",
    url_sub: "https://violeta.zappingtv.com/block/sr-cfinal/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7071": {
    id: 7071,
    name: "Mega Super Resolution",
    image: "mega4k",
    desc_short: "Emocionantes programas para toda la familia.",
    package_id: 79,
    number: 3,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: true,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/mega/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/mega/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "7091": {
    id: 7091,
    name: "Fanatiz1",
    image: "fanatizcl",
    desc_short: "Fanatiz1: fútbol sudamericano en vivo 24/7.",
    package_id: 581,
    number: 52,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: true,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/fanatizcl/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/fanatizcl/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "73": {
    id: 73,
    name: "UCV",
    image: "ucv3",
    desc_short: "Entretención y cultura",
    package_id: 76,
    number: 169,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/ucv3o/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/ucv3o/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "74": {
    id: 74,
    name: "BBC World News",
    image: "bbcnews",
    desc_short: "Noticias Internacionales",
    package_id: 871,
    number: 134,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/bbcwn/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/bbcwn/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "742": {
    id: 742,
    name: "TVN3",
    image: "tvn3",
    desc_short: "Canal retro",
    package_id: 81,
    number: 25,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/tvn3/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/tvn3/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "80": {
    id: 80,
    name: "NTN24",
    image: "ntn24",
    desc_short: "Noticias de Colombia y Venezuela",
    package_id: 691,
    number: 139,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/ntn24/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/ntn24/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "91": {
    id: 91,
    name: "13REC",
    image: "rec",
    desc_short: "Canal retro de la televisión chilena",
    package_id: 871,
    number: 24,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/rectv/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/rectv/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "92": {
    id: 92,
    name: "CDO Premium",
    image: "cdo",
    desc_short: "Canal del Deporte Olímpico",
    package_id: 581,
    number: 51,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/cdop/live1/playlist.m3u8",
    url_sub: "https://ringeling.zappingtv.com/v1/cdop/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
  "94": {
    id: 94,
    name: "Zapping Music Classics",
    image: "music-classics",
    desc_short: "Clásicos de los 90s y 2000s",
    package_id: 551,
    number: 203,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    start_over: false,
    token: "a",
    url: "https://ringeling.zappingtv.com/v1/zm-classics/live1/playlist.m3u8",
    url_sub:
      "https://ringeling.zappingtv.com/v1/zm-classics/live1/playlist.m3u8",
    parental: 0,
    locked: false,
  },
};
