export const canalesZapping = {
  '10': {
    id: 10,
    name: 'Cámara de Diputados TV',
    image: 'camara',
    desc_short: 'Señal oficial de la Cámara de Diputados',
    package_id: 76,
    number: 160,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/diputados/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/diputados/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '11': {
    id: 11,
    name: 'TV Senado',
    image: 'tvsenado',
    desc_short: 'Señal oficial del Senado',
    package_id: 102,
    number: 161,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/senado/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/senado/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '12': {
    id: 12,
    name: 'T13',
    image: 't13',
    desc_short: 'Noticias de Chile y el mundo 24/7',
    package_id: 76,
    number: 13,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/132/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/132/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '126': {
    id: 126,
    name: 'TNT Series',
    image: 'tntseries',
    desc_short: 'Cine y Series',
    package_id: 581,
    number: 102,
    has_sub: true,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tntseries/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tntseries/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '13': {
    id: 13,
    name: 'TV +',
    image: 'tvmas',
    desc_short: 'Entretención',
    package_id: 571,
    number: 29,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tvm/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tvm/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '134': {
    id: 134,
    name: 'Radio Romantica',
    image: 'romantica',
    desc_short: 'Radio Chile',
    package_id: 671,
    number: 196,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/romantica/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/romantica/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '135': {
    id: 135,
    name: 'Carolina TV',
    image: 'carolinatv',
    desc_short: 'Radio Online Chile',
    package_id: 102,
    number: 195,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/carolinatv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/carolinatv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '136': {
    id: 136,
    name: 'Radio Infinita',
    image: 'radioinfinita',
    desc_short: 'Radio Chile',
    package_id: 76,
    number: 197,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/infinitatv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/infinitatv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '142': {
    id: 142,
    name: 'CNN Chile',
    image: 'cnnchile',
    desc_short: 'Noticias de Chile',
    package_id: 76,
    number: 8,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/cnnchile/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/cnnchile/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '156': {
    id: 156,
    name: 'TNT Sports',
    image: 'tntsports3',
    desc_short: 'Deportes',
    package_id: 76,
    number: 35,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tntsports3/sport.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/tntsports3/sport.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '1622': {
    id: 1622,
    name: 'Mega 2',
    image: 'mega2',
    desc_short: 'Actualidad, deporte y tendencias.',
    package_id: 81,
    number: 27,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/mega2/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/mega2/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '164': {
    id: 164,
    name: 'TNT Sports Premium',
    image: 'tntsportshd',
    desc_short: 'Deportes',
    package_id: 92,
    number: 36,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tntsportshd/sport.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/tntsportshd/sport.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '165': {
    id: 165,
    name: 'La Red',
    image: 'lared',
    desc_short: 'Entretención',
    package_id: 571,
    number: 28,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/lared/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/lared/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '17': {
    id: 17,
    name: 'Canal 9 Bío-Bío',
    image: 'canal9',
    desc_short: 'Señal de la Octava Región',
    package_id: 102,
    number: 179,
    has_sub: false,
    has_hd: false,
    catch_up: 0,
    reverse_epg: 0,
    token: 'none',
    url: 'https://unlimited1-cl-isp.dps.live/c9/c9.smil/playlist.m3u8',
    url_sub: 'https://unlimited1-cl-isp.dps.live/c9/c9.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '171': {
    id: 171,
    name: 'ESPN 3',
    image: 'espn3',
    desc_short: 'Donde el deporte nunca se detiene.',
    package_id: 571,
    number: 47,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/espn3/sport.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/espn3/sport.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '1712': {
    id: 1712,
    name: 'Zapping Music Punch',
    image: 'music-punch',
    desc_short: 'El mejor carrete tecno directo en tu hogar.',
    package_id: 571,
    number: 204,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-punch/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-punch/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '1722': {
    id: 1722,
    name: 'Zapping Music Soft Pop',
    image: 'music-softpop',
    desc_short: 'El mejor pop tranqui en tu hogar',
    package_id: 571,
    number: 202,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-softpop/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-softpop/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '173': {
    id: 173,
    name: 'ETC',
    image: 'etc',
    desc_short: 'Canal del animé',
    package_id: 40,
    number: 90,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/etctv/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/etctv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '181': {
    id: 181,
    name: 'UESTV',
    image: 'uestv',
    desc_short: 'Canal local',
    package_id: 571,
    number: 172,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'none',
    url: 'https://ringeling.zappingtv.com/v1/uestvcl/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/uestvcl/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '182': {
    id: 182,
    name: 'STGO.TV',
    image: 'stgotv',
    desc_short: 'Canal local',
    package_id: 81,
    number: 173,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/stgotv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/stgotv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '184': {
    id: 184,
    name: 'NTV',
    image: 'ntv',
    desc_short: 'Canal infantil familiar',
    package_id: 102,
    number: 84,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tveducachile/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/tveducachile/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '188': {
    id: 188,
    name: 'Cuenta Cuentos',
    image: 'ccuentos',
    desc_short: 'Cuentos infantiles.',
    package_id: 40,
    number: 80,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/cuenta_cuentos/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/cuenta_cuentos/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '189': {
    id: 189,
    name: 'Zapping Music LOF-AI',
    image: 'music-lofi',
    desc_short:
      'Solo pasa acá a relajarte con la mejor selección de música Lo-Fi',
    package_id: 571,
    number: 206,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-lofi/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-lofi/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '202': {
    id: 202,
    name: 'Bio Bio TV',
    image: 'biobio',
    desc_short: 'Canal local',
    package_id: 571,
    number: 10,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/biobiotv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/biobiotv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '203': {
    id: 203,
    name: 'ITV',
    image: 'itv',
    desc_short: 'Canal regional',
    package_id: 102,
    number: 185,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/itv/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/itv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '204': {
    id: 204,
    name: 'Tevex',
    image: 'tevex',
    desc_short: 'Canal local',
    package_id: 571,
    number: 162,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tevex/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tevex/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '208': {
    id: 208,
    name: 'Radio Hoy',
    image: 'radiohoy',
    desc_short: 'El Sonido de tu vida.',
    package_id: 81,
    number: 198,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/radiohoy/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/radiohoy/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '221': {
    id: 221,
    name: 'Nexoplay',
    image: 'nexoplay',
    desc_short: 'Canal Esports 24/7',
    package_id: 40,
    number: 95,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/nexoplay/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/nexoplay/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '222': {
    id: 222,
    name: 'Zapping Mix',
    image: 'zmix',
    desc_short: 'TVN, Chilevisión, Mega y Canal 13',
    package_id: 581,
    number: 18,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zc1/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/zc1/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '225': {
    id: 225,
    name: 'Zapping Channel',
    image: 'zapping-channel1',
    desc_short: 'Canal de los Zappiners',
    package_id: 571,
    number: 17,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zc2/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/zc2/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '232': {
    id: 232,
    name: 'HBO',
    image: 'hbo',
    desc_short: 'Series y películas',
    package_id: 83,
    number: 145,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbo/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbo/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '233': {
    id: 233,
    name: 'HBO 2',
    image: 'hbo2',
    desc_short: 'Series y películas',
    package_id: 571,
    number: 100,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbo2/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbo2/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '234': {
    id: 234,
    name: 'HBO Plus',
    image: 'hboplus',
    desc_short: 'Series y películas',
    package_id: 581,
    number: 148,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hboplus/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hboplus/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '235': {
    id: 235,
    name: 'HBO Pop',
    image: 'hbopop',
    desc_short: 'Series y películas',
    package_id: 83,
    number: 151,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbopop/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbopop/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '236': {
    id: 236,
    name: 'HBO Mundi',
    image: 'hbomundi',
    desc_short: 'Series y películas',
    package_id: 581,
    number: 152,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbomundi/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbomundi/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '237': {
    id: 237,
    name: 'HBO Xtreme',
    image: 'hboxtreme',
    desc_short: 'Series y películas',
    package_id: 83,
    number: 149,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hboxtreme/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hboxtreme/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '239': {
    id: 239,
    name: 'HBO Family',
    image: 'hbofamily',
    desc_short: 'Series y películas',
    package_id: 581,
    number: 147,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbofamily/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbofamily/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '2391': {
    id: 2391,
    name: 'CHV Noticias',
    image: 'chvnoticias',
    desc_short: 'Noticias',
    package_id: 76,
    number: 11,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/chvnoticias/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/chvnoticias/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '240': {
    id: 240,
    name: 'HBO Signature',
    image: 'hbosignature',
    desc_short: 'Series y películas',
    package_id: 83,
    number: 150,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbosignature/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbosignature/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '245': {
    id: 245,
    name: 'Universal Premier',
    image: 'universalpremier',
    desc_short: 'Series y Peliculas',
    package_id: 84,
    number: 153,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/universalpremier/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/universalpremier/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '246': {
    id: 246,
    name: 'Universal Reality',
    image: 'universalreality',
    desc_short: 'Series y Peliculas',
    package_id: 84,
    number: 154,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/universalreality/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/universalreality/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '247': {
    id: 247,
    name: 'Universal Crime',
    image: 'universalcrime',
    desc_short: 'Series y Peliculas',
    package_id: 84,
    number: 156,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/universalcrime/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/universalcrime/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '248': {
    id: 248,
    name: 'Universal Comedy',
    image: 'universalcomedy',
    desc_short: 'Series y Peliculas',
    package_id: 84,
    number: 157,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/universalcomedy/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/universalcomedy/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '249': {
    id: 249,
    name: 'Universal Cinema',
    image: 'universalcinema',
    desc_short: 'Series y Peliculas',
    package_id: 84,
    number: 155,
    has_sub: true,
    has_hd: true,
    catch_up: 2,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/universalcinema/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/universalcinema/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '2551': {
    id: 2551,
    name: 'Meganoticias',
    image: 'meganoticias',
    desc_short:
      'Canal chileno de noticias y eventos nacionales e internacionales',
    package_id: 81,
    number: 9,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/meganoticias/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/meganoticias/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '257': {
    id: 257,
    name: 'Playboy',
    image: 'playboy',
    desc_short: 'Adultos',
    package_id: 85,
    number: 144,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/playboy/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/playboy/auto.smil/playlist.m3u8',
    parental: 1,
    locked: false
  },
  '258': {
    id: 258,
    name: 'Zapping Music Uwu',
    image: 'music-uwu',
    desc_short: 'Lo mejor del pop Coreano y Japonés',
    package_id: 28,
    number: 205,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-uwu/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-uwu/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '279': {
    id: 279,
    name: 'TVR',
    image: 'tvr',
    desc_short: 'Televisión Regional de Chile',
    package_id: 76,
    number: 175,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tvr/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tvr/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '280': {
    id: 280,
    name: 'TVU',
    image: 'tvu',
    desc_short: 'Televisión Universidad de Concepción',
    package_id: 81,
    number: 180,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tvu/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tvu/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '281': {
    id: 281,
    name: 'UATV',
    image: 'uatv',
    desc_short: 'UATV',
    package_id: 76,
    number: 181,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/uatv/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/uatv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '282': {
    id: 282,
    name: 'Antofagasta TV',
    image: 'antofagastatv',
    desc_short: 'Antofagasta TV',
    package_id: 76,
    number: 167,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/antofagastatv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/antofagastatv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '283': {
    id: 283,
    name: 'VTV Quillota',
    image: 'vtvquillota',
    desc_short: 'VTV Quillota',
    package_id: 102,
    number: 170,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/vtvquillota/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/vtvquillota/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '284': {
    id: 284,
    name: 'Canal 2 Quellón',
    image: 'c2quellon',
    desc_short: 'Canal 2 Quellón',
    package_id: 76,
    number: 183,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/c2quellon/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/c2quellon/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '285': {
    id: 285,
    name: 'TeleAngol',
    image: 'teleangol',
    desc_short: 'TeleAngol',
    package_id: 81,
    number: 182,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/teleangol/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/teleangol/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '286': {
    id: 286,
    name: 'Canal 2 San Antonio',
    image: 'c2sanantonio',
    desc_short: 'Canal 2 San Antonio',
    package_id: 76,
    number: 178,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/c2sanantonio/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/c2sanantonio/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '287': {
    id: 287,
    name: 'Patagonia Radio Televisión',
    image: 'patagoniartv',
    desc_short: 'Patagonia Radio Televisión',
    package_id: 81,
    number: 186,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/patagoniartv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/patagoniartv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '288': {
    id: 288,
    name: 'Senpai TV',
    image: 'senpaitv',
    desc_short: 'Canal de animación japonesa',
    package_id: 28,
    number: 91,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/senpaitv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/senpaitv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '289': {
    id: 289,
    name: 'Mega Ficción',
    image: 'megaficcion',
    desc_short: 'Variedad de series y producciones de ficción',
    package_id: 76,
    number: 26,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/megaficcion/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/megaficcion/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '290': {
    id: 290,
    name: 'El Centro TV',
    image: 'centrotv',
    desc_short: 'El Centro TV',
    package_id: 581,
    number: 174,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/centrotv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/centrotv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '291': {
    id: 291,
    name: 'Mi Radio TV',
    image: 'miradiotv',
    desc_short: 'Mi Radio TV',
    package_id: 76,
    number: 165,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/miradiotv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/miradiotv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '292': {
    id: 292,
    name: 'Agricultura TV ',
    image: 'agriculturatv',
    desc_short: 'Agricultura TV ',
    package_id: 102,
    number: 166,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/agriculturatv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/agriculturatv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '293': {
    id: 293,
    name: 'ISB',
    image: 'isb',
    desc_short: 'ISB',
    package_id: 76,
    number: 176,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/isb/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/isb/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '3': {
    id: 3,
    name: 'Canal 13',
    image: 'canal13',
    desc_short: 'Variedad de programas para toda la familia.',
    package_id: 76,
    number: 22,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/13/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/13/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '3151': {
    id: 3151,
    name: 'La Metro FM',
    image: 'lametro',
    desc_short: 'Noticias del entretenimiento y segmentos interactivos.',
    package_id: 76,
    number: 194,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/lametro/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/lametro/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '332': {
    id: 332,
    name: 'Zapping Sports',
    image: 'zappingsports',
    desc_short: 'Deporte exclusivo por Zapping Sports',
    package_id: 571,
    number: 39,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zappingsports/sport.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zappingsports/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '3851': {
    id: 3851,
    name: 'Zapping Popcorn',
    image: 'zm-popcorn',
    desc_short: 'Los mejores trailers 24/7.',
    package_id: 79,
    number: 99,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-popcorn/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-popcorn/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '3911': {
    id: 3911,
    name: 'HBO 2',
    image: 'hbo2b',
    desc_short: 'Series y películas',
    package_id: 581,
    number: 146,
    has_sub: true,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/hbo2/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/hbo2/en/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '4': {
    id: 4,
    name: 'Mega',
    image: 'mega',
    desc_short: 'Emocionantes programas para toda la familia.',
    package_id: 76,
    number: 20,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/mega/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/mega/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '4771': {
    id: 4771,
    name: 'Marga Marga TV',
    image: 'margamargatv',
    desc_short: 'Señal de la 5ta región. Canal de entretención',
    package_id: 79,
    number: 168,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/margamargatv/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/margamargatv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '4781': {
    id: 4781,
    name: 'La Nuestra, radio streaming',
    image: 'lanuestracl',
    desc_short: 'Entretenimiento y compañía para divertirte todo el día',
    package_id: 76,
    number: 193,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/lanuestracl/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/lanuestracl/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '4791': {
    id: 4791,
    name: 'Visión Plus TV',
    image: 'visionplus',
    desc_short: 'Entretenimiento, educación y cultura',
    package_id: 102,
    number: 171,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/visionplus/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/visionplus/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '4861': {
    id: 4861,
    name: 'UChileTV',
    image: 'uchiletvcl',
    desc_short: 'Actualidad y cultura nacional.',
    package_id: 551,
    number: 163,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/uchiletvcl/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/uchiletvcl/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '5': {
    id: 5,
    name: 'TVN',
    image: 'tvn',
    desc_short: 'Diversidad de contenidos televisivos.',
    package_id: 81,
    number: 19,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tvno/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tvno/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '51': {
    id: 51,
    name: '13C',
    image: '13cable',
    desc_short: 'Cultura, viajes y cocina',
    package_id: 581,
    number: 23,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/13c/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/13c/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '52': {
    id: 52,
    name: '24 Horas',
    image: '24horas',
    desc_short: 'Noticias de Chile y el mundo 24/7',
    package_id: 571,
    number: 7,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/24h/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/24h/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '57': {
    id: 57,
    name: 'Zapping Music Chile',
    image: 'music-chile',
    desc_short: 'Lo más escuchado de la música chilena',
    package_id: 81,
    number: 209,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-chile/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-chile/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '6': {
    id: 6,
    name: 'Chilevisión',
    image: 'chv',
    desc_short: 'Entretenimiento, noticias y deportes.',
    package_id: 102,
    number: 21,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/chv/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/chv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '60': {
    id: 60,
    name: 'Zapping Music Retro',
    image: 'music-retro',
    desc_short: 'La década dorada de los 80s',
    package_id: 102,
    number: 200,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-retro/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-retro/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '61': {
    id: 61,
    name: 'Zapping Music Indie',
    image: 'music-indie',
    desc_short: 'Dosis de sonido alternativo',
    package_id: 102,
    number: 201,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-indie/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-indie/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '62': {
    id: 62,
    name: 'Zapping Music Hits',
    image: 'music-hits',
    desc_short: 'Los mejores éxitos de ayer y hoy ',
    package_id: 76,
    number: 208,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-hits/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-hits/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '63': {
    id: 63,
    name: 'Zapping Music Rock',
    image: 'music-rock',
    desc_short: 'Guitarras y rock del mundo',
    package_id: 76,
    number: 207,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-rock/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-rock/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '7': {
    id: 7,
    name: 'Teletrak',
    image: 'teletrak',
    desc_short: 'Vive la hípica',
    package_id: 561,
    number: 52,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/teletrak/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/teletrak/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '73': {
    id: 73,
    name: 'UCV',
    image: 'ucv3',
    desc_short: 'Entretención y cultura',
    package_id: 76,
    number: 169,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/ucv3o/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/ucv3o/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '742': {
    id: 742,
    name: 'TVN3',
    image: 'tvn3',
    desc_short: 'Canal retro',
    package_id: 79,
    number: 25,
    has_sub: false,
    has_hd: true,
    catch_up: 7,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tvn3/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/tvn3/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '91': {
    id: 91,
    name: 'REC TV',
    image: 'rec',
    desc_short: 'Canal retro de la televisión chilena',
    package_id: 76,
    number: 24,
    has_sub: false,
    has_hd: true,
    catch_up: 1,
    reverse_epg: 1,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/rectv/auto.smil/playlist.m3u8',
    url_sub: 'https://ringeling.zappingtv.com/v1/rectv/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '93': {
    id: 93,
    name: 'TVMas2',
    image: 'tvmas2',
    desc_short: 'Entretención',
    package_id: 581,
    number: 164,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/tateti/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/tateti/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  },
  '94': {
    id: 94,
    name: 'Zapping Music Classics',
    image: 'music-classics',
    desc_short: 'Clásicos de los 90s y 2000s',
    package_id: 76,
    number: 203,
    has_sub: false,
    has_hd: true,
    catch_up: 0,
    reverse_epg: 0,
    token: 'a',
    url: 'https://ringeling.zappingtv.com/v1/zm-classics/auto.smil/playlist.m3u8',
    url_sub:
      'https://ringeling.zappingtv.com/v1/zm-classics/auto.smil/playlist.m3u8',
    parental: 0,
    locked: false
  }
};
