import { BsCamera, BsCameraFill } from "react-icons/bs";
import { SourcesMap } from ".";

const cameraIcon = <BsCameraFill key="camara" />;
export const camarasSources: SourcesMap = {
  PLAZAITALIA_CIMA: {
    slug: "PLAZAITALIA_CIMA",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠPLAZA ITALIA (Galeria Cima)",
    youtubeChannelId: "UC4GOcOKkEefz5NamN4WyMFg",
    name: "PLAZA DIGNIDAD",
  },
  LEDRIUM_1: {
    slug: "LEDRIUM_1",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠPROVIDENCIA (Ledrium)",
    youtubeVideoId: "mGxX5PfREPA",
  },
  OSORNO: {
    slug: "OSORNO",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠOSORNO PLAZA ARMAS",
    name: "OSORNO PLAZA ARMAS",
    youtubeChannelId: "UCD7sqegDNyZxmdnCj6xqH6g",
  },
  VALPARAISO: {
    slug: "VALPARAISO",
    name: "VALPARAISO",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml:
      'ﾠVALPARAISOﾠ<img style="height: 15px; width:auto:" src="imagenes/Icono_SeñalOcasional.svg"></img>',
    youtubeChannelId: "UCqSSE82uHv1rkR3Tj9lTx1w",
  },
  IQUIQUE_1: {
    slug: "IQUIQUE_1",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠIQUIQUE PLAYA CAVANCHA",
    m3u8Url: "https://s20.ipcamlive.com/streams/14nke3idvqrw2waqb/stream.m3u8",
    name: "IQUIQUE",
  },
  IQUIQUE_2: {
    slug: "IQUIQUE_2",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠIQUIQUE PLAYA HUAYQUIQUE",
    iframeSrc:
      "https://g3.ipcamlive.com/player/player.php?alias=huayquique&autoplay=true",
    name: "IQUIQUE",
  },

  PARQUEMET_CUMBRE: {
    slug: "PARQUEMET_CUMBRE",
    name: "PARQUEMET CUMBRE",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠPARQUEMET CUMBRE",
    m3u8Url: "https://s13.ipcamlive.com/streams/0du4ap2gbyr0xdsmk/stream.m3u8",
  },
  PARQUEMET_TERRAZA: {
    slug: "PARQUEMET_TERRAZA",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠPARQUEMET TERRAZA",
    m3u8Url: "https://s12.ipcamlive.com/streams/0c7esvvabpbjkuqxj/stream.m3u8",
  },
  Times_Square_4_1560_BROADWAY: {
    slug: "Times_Square_4_1560_BROADWAY",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠTIMES SQUARE 4",
    youtubeVideoId: "rZjblGbbCmE",
    name: "TIMES SQUARE: 1540 BROADWAY",
  },
  CNN1: {
    slug: "CNN1",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠOcasional - CNN 1",
    m3u8Url:
      "https://unlimited2-cl-isp.dps.live/cnnprensa/cnnprensa.smil/playlist.m3u8",
  },

  IQUIQUE_3: {
    slug: "IQUIQUE_3",
    flag: "cl",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠIQUIQUE PLAYA BELLAVISTA",
    name: "IQUIQUE",
    iframeSrc:
      "https://g3.ipcamlive.com/player/player.php?alias=lapunta2&autoplay=true",
  },

  CAPITOLIO_EEUU_1: {
    slug: "CAPITOLIO_EEUU_1",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠCAPITOLIO EEUU",
    name: "CAPITOLIO EEUU",
    m3u8Url: "https://capcam-f.akamaihd.net/i/capcam_1@76463/master.m3u8",
  },
  NYC_Brooklyn_Bridge: {
    slug: "NYC_Brooklyn_Bridge",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠNYC BROOKLYN BRIDGE",
    youtubeVideoId: "KGuCGd726RA",
    name: "NYC BROOKLYN BRIDGE",
  },
  Lower_Manhattan_New_York_Harbor: {
    slug: "Lower_Manhattan_New_York_Harbor",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠNYC LOWER MANHATTAN",
    youtubeVideoId: "Vj0XKu6AoOw",
    name: "NYC LOWER MANHATTAN & NEW YORK HARBOR",
  },
  Times_Square_1: {
    slug: "Times_Square_1",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠTIMES SQUARE 1",
    youtubeVideoId: "AdUw5RdyZxI",
    name: "TIMES SQUARE",
  },
  Times_Square_2_DUFFY_SQUARE: {
    slug: "Times_Square_2_DUFFY_SQUARE",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠTIMES SQUARE 2",
    youtubeChannelId: "mNawBricEYw",
    name: "TIMES SQUARE: DUFFY SQUARE",
  },
  Times_Square_3_EXPRESS_VIEW: {
    slug: "Times_Square_3_EXPRESS_VIEW",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠTIMES SQUARE 3",
    youtubeChannelId: "6dtpPYTQaSQ",
    name: "TIMES SQUARE: EXPRESS VIEW",
  },
  Casa_Blanca: {
    slug: "Casa_Blanca",
    youtubeChannelId: "GGsBUm8uar0",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠCASA BLANCA",
    name: "CASA BLANCA",
  },
  WHITE_HOUSE_1: {
    slug: "WHITE_HOUSE_1",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠWHITE HOUSE",
    youtubeVideoId: "T5zRi2J0uYg",
  },
  Times_Square_2: {
    slug: "Times_Square_2",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠTIMES SQUARE: EXPRESS VIEW",
    youtubeVideoId: "OBmXqlPxtAQ",
  },
  Times_Square_3: {
    slug: "Times_Square_3",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠTIMES SQUARE: 1560 BROADWAY",
    youtubeVideoId: "4qyZLflp-sI",
  },
  LasVegas_1: {
    slug: "LasVegas_1",
    flag: "us",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠLAS VEGAS",
    youtubeChannelId: "oy3tQ5Hacm8",
  },
  Four_Seasons_Hotel_Buenos_Aires: {
    slug: "Four_Seasons_Hotel_Buenos_Aires",
    flag: "ar",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠFOUR SEASONS HOTEL BS.As",
    youtubeChannelId: "if91GyWP3zQ",
  },
  Ushuaia: {
    slug: "Ushuaia",
    flag: "ar",
    titleIcons: [cameraIcon],
    titleHtml: "ﾠUSHUAIA",
    iframeSrc: "/Monitores/Señal_CAMARA_USHUAIA.html",
  },
  VolcanLaPalma: {
    slug: "VolcanLaPalma",
    flag: "es",
    titleIcons: [cameraIcon],
    titleHtml:
      'ﾠVOLCAN LA PALMAﾠ<img style="height: 15px; width:auto:" src="imagenes/Icono_SeñalOcasional.svg"></img>',
    m3u8Url: "https://rtvc-oca1.flumotion.com/playlist.m3u8",
    name: "VOLCAN LA PALMAㅤ",
  },
};
